[theme]
primaryColor="#FF4B4B"  # Custom primary color
backgroundColor="#90ee90"  # Main background color
secondaryBackgroundColor="#F0F2F6"  # Sidebar background color
textColor="#31333F"  # Text color
font="sans serif"  # Font style